import { ProductProps } from "@/components/single-product";

export const navbarLinks = [
  {
    text: "Home",
    link: "/",
  },
  {
    text: "About us",
    link: "/about",
  },
  {
    text: "Cakes & Pastries",
    link: "/cakes",
  },
  {
    text: "Wigs & Braids",
    link: "/wigs",
  },
  {
    text: "Accessories",
    link: "/accessories",
  },
  {
    text: "FAQ’s",
    link: "/faqs",
  },
];

export const bannerData = [
  {
    subtitle: "DELICIOUS CAKES FOR YOU! ",
    title: "We  give you a whole new delightsome  cake experience ",
    text: "HOSTRUCT CakenPastries creates custom cakes and pastries in Uk, crafted with love, creativity, and premium ingredients—perfect for birthdays, weddings, and special celebrations.",
    linkText: "See Cakes",
    link: "/cakes",
    number: 500,
    image: "/images/cake-banner.png",
  },
  {
    subtitle: "Your perfect wig or braid starts here!  ",
    title: "Bold looks. Beautiful you. Wigs and braids crafted to elevate your style.  ",
    text: "From natural glam to bold looks, HOSTRUCT Wigs & Braids creates high-quality hairpieces crafted for comfort, beauty, and lasting confidence and style",
    linkText: "See wigs and braids",
    link: "/wigs",
    number: 200,
    image: "/images/wig-banner.png",
  },
  {
    subtitle: "Own your style with every detail!  ",
    title: "From subtle sparkle to bold flair—accessories that complete your look.",
    text: "Discover stylish accessories made with love, bold style and craftsmanship—perfect for adding elegance to your everyday look or special celebration and events",
    linkText: "See Accessories",
    link: "/accessories",
    number: 200,
    image: "/images/access-banner.png",
  },
];

type Props = {
  cake: ProductProps[];
  wig: ProductProps[];
  access: ProductProps[];
};

export const productData: Props = {
  cake: [
    {
      src: "/images/cake1.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake1",
    },
    {
      src: "/images/cake2.png",
      title: "Character Cake",
      text: "Sweet baked Cake",
      price: 70,
      type: "cakes",
      id: "cake2",
    },
    {
      src: "/images/cake3.png",
      title: "Wedding Cake",
      text: "Sweet baked Cake",
      price: 110,
      type: "cakes",
      id: "cake3",
    },
    {
      src: "/images/cake4.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake4",
    },
    {
      src: "/images/cake5.png",
      title: "Occasion cake",
      text: "Sweet baked Cake",
      price: 75,
      type: "cakes",
      id: "cake5",
    },
    {
      src: "/images/cake6.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake6",
    },
    {
      src: "/images/cake7.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake7",
    },
    {
      src: "/images/cake8.png",
      title: "Football themed cake ",
      text: "Sweet baked Cake",
      price: 29,
      type: "cakes",
      id: "cake8",
    },
    {
      src: "/images/cake9.png",
      title: "Character Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake9",
    },
    {
      src: "/images/cake10.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake10",
    },
    {
      src: "/images/cake11.png",
      title: "Character Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake11",
    },
    {
      src: "/images/cake12.png",
      title: "Character Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake12",
    },
    {
      src: "/images/cake13.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake13",
    },
    {
      src: "/images/cake14.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake14",
    },
    {
      src: "/images/cake15.png",
      title: "Chocolate Ganache celebration cake",
      text: "Sweet baked Cake",
      price: 70,
      type: "cakes",
      id: "cake15",
    },
    {
      src: "/images/cake16.png",
      title: "Cup Cakes",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake16",
    },
    {
      src: "/images/cake17.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake17",
    },
    {
      src: "/images/cake18.png",
      title: "Character cake",
      text: "Sweet baked Cake",
      price: 70,
      type: "cakes",
      id: "cake18",
    },
    {
      src: "/images/cake20.png",
      title: "Birthday Cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake20",
    },
    {
      src: "/images/cake21.png",
      title: "Birthday cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake21",
    },
    {
      src: "/images/cake23.png",
      title: "Birthday cake",
      text: "Sweet baked Cake",
      price: 60,
      type: "cakes",
      id: "cake23",
    },
    {
      src: "/images/cake22.png",
      title: "Arsenal-Themed Celebration Cake",
      text: "Sweet baked Cake",
      price: 80,
      type: "cakes",
      id: "cake22",
    },
    {
      src: "/images/cake19.png",
      title: "Arsenal-Themed Celebration Cake",
      text: "Sweet baked Cake",
      price: 80,
      type: "cakes",
      id: "cake19",
    },
    {
      src: "/images/cake24.png",
      title: "Chocolate Ganache celebration cake",
      text: "Sweet baked Cake",
      price: 70,
      type: "cakes",
      id: "cake24",
    },
  ],
  wig: [
    {
      src: "/images/wig1.png",
      title: "Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig1",
    },
    {
      src: "/images/wig2.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig2",
    },
    {
      src: "/images/wig3.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig3",
    },
    {
      src: "/images/wig4.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig4",
    },
    {
      src: "/images/wig5.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig5",
    },
    {
      src: "/images/wig6.png",
      title: "Braided wigs",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 45,
      type: "wigs",
      id: "wig6",
    },
    {
      src: "/images/wig7.png",
      title: "Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig7",
    },
    {
      src: "/images/wig8.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig8",
    },
    {
      src: "/images/wig9.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig9",
    },
    {
      src: "/images/wig10.png",
      title: "Braids",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig10",
    },
    {
      src: "/images/wig11.png",
      title: "Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig11",
    },
    {
      src: "/images/wig12.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig12",
    },
    {
      src: "/images/wig13.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig13",
    },
    // {
    //   src: "/images/wig14.png",
    //   title: "14' Blend pixie with human hair frontal.",
    //   text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
    //   price: 50,
    //   type: "wigs",
    //   id: "wig14",
    // },
    {
      src: "/images/wig15.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig15",
    },
    {
      src: "/images/wig16.png",
      title: "Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig16",
    },
    {
      src: "/images/wig17.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig17",
    },
    {
      src: "/images/wig18.png",
      title: "Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig18",
    },
    {
      src: "/images/wig19.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig19",
    },
    {
      src: "/images/wig20.png",
      title: "Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig20",
    },
    {
      src: "/images/wig21.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig21",
    },
    {
      src: "/images/wig22.png",
      title: "Full frontal Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig22",
    },
    {
      src: "/images/wig23.png",
      title: "Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig23",
    },
    {
      src: "/images/wig24.png",
      title: "12' human hair deepwave",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 55,
      type: "wigs",
      id: "wig24",
    },
    {
      src: "/images/wig25.png",
      title: "10' Kim k human hair bob",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 45,
      type: "wigs",
      id: "wig25",
    },
    {
      src: "/images/wig26.png",
      title: "12' human hair bob wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 55,
      type: "wigs",
      id: "wig26",
    },
    {
      src: "/images/wig27.png",
      title: "20' colour 2 blend kinky straight ",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 29,
      type: "wigs",
      id: "wig27",
    },
    {
      src: "/images/wig28.png",
      title: "14' Blend pixie with human hair frontal",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 29,
      type: "wigs",
      id: "wig28",
    },
    {
      src: "/images/wig29.png",
      title: "Braided wig",
      text: "Wig is made of high-quality, heat-resistant synthetic fiber ",
      price: 60,
      type: "wigs",
      id: "wig29",
    },
    {
      src: "/images/access24.png",
      title: "Chapter2000",
      text: "Quality accessories",
      price: 7,
      type: "wigs",
      id: "wig30",
    },
    {
      src: "/images/access25.png",
      title: "Hair Care",
      text: "Quality accessories",
      price: 6,
      type: "wigs",
      id: "wig31",
    },
    {
      src: "/images/access26.png",
      title: "Hair Care",
      text: "Quality accessories",
      price: 6,
      type: "wigs",
      id: "wig32",
    },
    {
      src: "/images/access27.png",
      title: "Shine n Jam",
      text: "Quality accessories",
      price: 5,
      type: "wigs",
      id: "wig33",
    },
    {
      src: "/images/access28.png",
      title: "Hair Care",
      text: "Quality accessories",
      price: 6,
      type: "wigs",
      id: "wig34",
    },
  ],
  access: [
    {
      src: "/images/access1.png",
      title: "Traditional bead",
      text: "Quality accessories",
      price: 70,
      type: "accessories",
      id: "accessories1",
    },
    {
      src: "/images/access2.png",
      title: "Hair Piece",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories2",
    },
    {
      src: "/images/access3.png",
      title: "Traditional Beads",
      text: "Quality accessories",
      price: 70,
      type: "accessories",
      id: "accessories3",
    },
    {
      src: "/images/access4.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories4",
    },
    {
      src: "/images/access5.png",
      title: "Traditional bead",
      text: "Quality accessories",
      price: 70,
      type: "accessories",
      id: "accessories5",
    },
    {
      src: "/images/access6.png",
      title: "Fascinator Hat",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories6",
    },
    {
      src: "/images/access7.png",
      title: "Head Gear",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories7",
    },
    {
      src: "/images/access8.png",
      title: "Head Gear",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories8",
    },
    {
      src: "/images/access9.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories9",
    },
    {
      src: "/images/access10.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories10",
    },
    {
      src: "/images/access11.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories11",
    },
    {
      src: "/images/access12.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories12",
    },
    {
      src: "/images/access13.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories13",
    },
    {
      src: "/images/access14.png",
      title: "Beaded Hair Accessories",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories14",
    },
    {
      src: "/images/access15.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories15",
    },
    {
      src: "/images/access16.png",
      title: "Fascinator Hat",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories16",
    },
    {
      src: "/images/access17.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 70,
      type: "accessories",
      id: "accessories17",
    },
    {
      src: "/images/access18.png",
      title: "Ankara Fascinators Hat",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories18",
    },
    {
      src: "/images/access19.png",
      title: "Head Gear",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories19",
    },
    {
      src: "/images/access20.png",
      title: "Traditional Wedding Beads",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories20",
    },
    {
      src: "/images/access21.png",
      title: "Traditional Wedding Beads",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories21",
    },
    {
      src: "/images/access22.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories22",
    },
    {
      src: "/images/access23.png",
      title: "Beaded earrings and necklaces",
      text: "Quality accessories",
      price: 30,
      type: "accessories",
      id: "accessories23",
    },
  ],
};

export const homeFaqs = [
  {
    question: "Do you deliver cakes?",
    answer:
      "Yes, we offer custom cakes for special occasions such as birthdays, weddings, and baby showers. Please let us know the details of your event and any specific requests you may have so that we can create the perfect cake for you.",
  },
  {
    question: "Can I request a custom design not listed on the website?",
    answer:
      "Yes, we offer custom cakes for special occasions such as birthdays, weddings, and baby showers. Please let us know the details of your event and any specific requests you may have so that we can create the perfect cake for you.",
  },
  {
    question: "Are your wigs 100% human hair?",
    answer:
      "Yes, we offer custom cakes for special occasions such as birthdays, weddings, and baby showers. Please let us know the details of your event and any specific requests you may have so that we can create the perfect cake for you.",
  },
  {
    question: "How long does it take to make a fascinator?",
    answer:
      "Yes, we offer custom cakes for special occasions such as birthdays, weddings, and baby showers. Please let us know the details of your event and any specific requests you may have so that we can create the perfect cake for you.",
  },
];

export const faqs = {
  cake: [
    {
      question: "How far in advance should I place my order?",
      answer: "2 weeks ",
    },
    {
      question: "Do you deliver cakes?",
      answer: "Yes, we deliver cakes",
    },
    {
      question: "Can I request a custom design not listed on the website?",
      answer:
        "Yes, we offer custom cakes for special occasions such as birthdays, weddings, and baby showers. Please let us know the details of your event and any specific requests you may have so that we can create the perfect cake for you.",
    },
    {
      question: "Are your cakes eggless or available in gluten-free options?",
      answer: "Yes, they are available in gluten free options.",
    },
  ],
  wig: [
    {
      question: "Are your wigs 100% human hair?",
      answer: "Yes, we have 100% human hair wigs and we also have those that are budget friendly.",
    },
    {
      question: "How do I care for and wash my wig?",
      answer: "You can reach out and we can explain how to do that in detail.",
    },
    {
      question: "Do you offer custom wig coloring or styling?",
      answer: "Yes, we offer custom wig coloring.",
    },
    {
      question: "Can I return a wig if it doesn't fit?",
      answer: "Yes, as long as the seal is still intact",
    },
  ],
  access: [
    {
      question: "Can I request a custom design to match my outfit?",
      answer: "Yes, you can.",
    },
    {
      question: "How long does it take to make a fascinator?",
      answer: "2 weeks ",
    },
    {
      question: "Do you deliver accessories nationwide?",
      answer: "Yes, we do",
    },
    {
      question: "Are your materials locally sourced?",
      answer: "Yes, they are",
    },
  ],
};

export type CartType = {
  src: string;
  title: string;
  description: string;
  size: string;
  price: number;
  count: number;
  id: string;
};

export type UserDetails = {
  fullName: string;
  email: string;
  phoneNumber: string;
  address: string;
  date: string;
  message: string;
};
